# Use postgres/example user/password credentials
version: '3.1'

services:

  db:
    image: "postgres:16-alpine"

    ports:
      - 5432:5432

    environment:
      - POSTGRES_USER=rails
      - POSTGRES_PASSWORD=rails
      - POSTGRES_DB=rails

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080