# Use postgres/example user/password credentials
version: '3.1'

services:

  db:
    image: "postgres:16-alpine"
    command: postgres -c listen_addresses='*'
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=rails
      - POSTGRES_PASSWORD=rails
      - POSTGRES_DB=rails
    healthcheck:
      test:
        ["CMD", "pg_isready", "--username", "rails", "--dbname", "rails"]
      interval: 3s
      timeout: 2s
      retries: 5